### ISSUE TITLE
ErrorException: User Deprecated: Accessing Doctrine\Common\Lexer\Token properties via ArrayAccess is deprecated, use the value, type or position property instead (Token.php:108 called by JsonSearch.php:69, https://github.com/doctrine/lexer/pull/79, package doctrine/lexer)

### ISSUE THREAD

**Issue by tourze** [ScientaNL/DoctrineJsonFunctions#93]
My composer.json file:

```
    "doctrine/dbal": "3.6.*",
    "scienta/doctrine-json-functions": "5.1.0",
```

**Comment by MalikOvaiz** [comment]
I have the same issue but I do not think it is due to DoctrineJsonFunctions.

I encountered the issue while upgrading Symfony to version 6.3.

It occurred while serializing the service response i.e 

`$serializer->serialize($someService->someServiceFunction($id), 'json')`

In my case, it is due to the package jms/serializer.

**Comment by Hikariii** [comment]
Fixed by https://github.com/ScientaNL/DoctrineJsonFunctions/pull/95
